"""Adding listeners to the UserGame model

Revision ID: 0736725e545b
Revises: 0b28bce3d11a
Create Date: 2024-05-15 20:10:08.155115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0736725e545b'
down_revision: Union[str, None] = '0b28bce3d11a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
