"""Add is_winner field to UserGame

Revision ID: 54bd4cbe9f56
Revises: 0736725e545b
Create Date: 2024-05-15 20:19:48.508618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bd4cbe9f56'
down_revision: Union[str, None] = '0736725e545b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game', sa.Column('is_winner', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_game', 'is_winner')
    # ### end Alembic commands ###
