"""Added ticket relationships

Revision ID: 5eac0b2e8ba0
Revises: 54bd4cbe9f56
Create Date: 2024-05-19 22:18:20.508363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eac0b2e8ba0'
down_revision: Union[str, None] = '54bd4cbe9f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotto_stats', sa.Column('prize_claimed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotto_stats', 'prize_claimed')
    # ### end Alembic commands ###
