"""Added game_id to game_config

Revision ID: 8c7a036ce7f0
Revises: c1653f5fb415
Create Date: 2024-05-07 20:34:03.608443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7a036ce7f0'
down_revision = 'c1653f5fb415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_game_config')
    with op.batch_alter_table('game_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('uq_game_config_game_id', 'game', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_config', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('game_id')

    op.create_table('_alembic_tmp_game_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_type_id', sa.INTEGER(), nullable=False),
    sa.Column('config_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('config_value', sa.VARCHAR(length=255), nullable=False),
    sa.Column('dateCreated', sa.DATETIME(), nullable=True),
    sa.Column('dateModified', sa.DATETIME(), nullable=True),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name='ug_game_config_game_id'),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
