"""Add game_type_id column to game table

Revision ID: 93aa37f1a93d
Revises: cad56abb7415
Create Date: 2024-05-06 21:39:16.915801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93aa37f1a93d'
down_revision = 'cad56abb7415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('entry_fee', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('winner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_players', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['winner_id'], ['id'])
        batch_op.create_foreign_key(None, 'game_type', ['game_type_id'], ['id'])
        batch_op.drop_column('num_players')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('num_players', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('max_players')
        batch_op.drop_column('winner_id')
        batch_op.drop_column('entry_fee')
        batch_op.drop_column('name')
        batch_op.drop_column('game_type_id')

    # ### end Alembic commands ###
