"""empty message

Revision ID: cad56abb7415
Revises:
Create Date: 2024-05-06 21:18:15.312112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad56abb7415'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('dateModified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_type_id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.String(length=255), nullable=False),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('dateModified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('entry_fee', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('winner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_players', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('uq_game_user', 'user', ['winner_id'], ['id'])
        batch_op.create_foreign_key('uq_game_game_type', 'game_type', ['game_type_id'], ['id'])
        batch_op.drop_column('num_players')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('num_players', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('max_players')
        batch_op.drop_column('winner_id')
        batch_op.drop_column('entry_fee')
        batch_op.drop_column('name')
        batch_op.drop_column('game_type_id')

    op.drop_table('game_config')
    op.drop_table('game_type')
    # ### end Alembic commands ###
